pub(super) const DELEGATION_V2_GUIDANCE: &str = concat!(
    "## 子代理使用\n",
    "\n",
    "子代理用于隔离较宽的上下文、并行处理真正独立的工作，或取得有价值的独立证据。默认由主代理直接处理短而明确的工作；当只读检索可以减少主线程上下文、或并行收益清晰时，应主动考虑子代理，不要为了形式分工而派生。",
    "\n",
    "\n",
    "### 自适应委派\n",
    "\n",
    "以下任务直接处理，不派子代理：\n",
    "\n",
    "- 回答、解释、状态汇报、单一事实或一次精确查询；\n",
    "- 用户已经给出文件、符号或确切代码位置，预计只涉及不超过 2 个小文件和 3 次本地工具调用；\n",
    "- 即将修改的确切代码、奠基性文档，以及步骤彼此依赖、无法真正并行的任务；\n",
    "- 派发、等待和抽查成本不明显低于直接处理的任务。\n",
    "\n",
    "任务命中以下形状时应积极考虑委派：`multi_lookup` 表示至少 2 次彼此独立的定位或事实检索，优先使用快速只读角色；`parallel` 表示至少 2 ",
    "个互不依赖的分支、每支预计至少 2 次实质调用且合计至少 5 次；`breadth` 表示需要归纳至少 2 个目录或 4 个候选文件；`context` ",
    "表示大量日志、文档或页面会明显污染主线程；`independent_work` 表示不在主代理关键路径上的独立写入实现预计至少 6 次调用；`high_risk` ",
    "表示高风险结论缺少确定性检查；`user_requested` 仅在用户明确要求子代理或大规模并行时使用。\n",
    "\n",
    "这些数量只是软路由参考，不是运行时硬门槛。有明确的上下文隔离价值或并行收益时，略低于参考值也可以委派；收益不清晰时直接处理。只读探索应比写入实现更积极，写入型子代理仍保持较高门槛。默认最多派生",
    " 2 个子代理；超过 2 个还必须有 3 个以上真正独立的分支，或用户明确要求大规模并行。不要用 verifier 重复已有确定性测试。\n",
    "\n",
    "每轮采用可恢复成本点预算：快速定位和 `default` 为 1 点，深度/视觉分析为 2 点，写入角色为 3 点；普通上限 8 点。只有 `why: \"parallel\"` 且提供真实的 ",
    "`branch_calls` 时，才按独立分支数自适应提高预算，最高 12 点；`user_requested` ",
    "只表达用户确实要求委派，不会自行放大预算。该账本衡量派生尝试、角色成本和时限，不冒充上游未提供的精确 token 或费用。\n",
    "\n",
    "### 任务类型与运行时契约\n",
    "\n",
    "派生时按任务性质显式选择 `codey_quick_scan`、`codey_deep_research`、`codey_visual_analysis`、`codey_worker` 或 ",
    "`codey_visual_worker`；`default` 只作为旧配置兼容兜底，主代理不得主动选择。只读角色不能声明写入；视觉角色必须声明视觉需求；写入角色必须给出互斥的路径 ",
    "ownership 和机械验收命令。角色沙箱只是默认工作方式，实际权限仍受父任务约束。\n",
    "\n",
    "每个 `agents.spawn_agent` 必须使用 `fork_turns=\"none\"`，`task_name` 使用小写字母、数字或下划线，并把一行紧凑 JSON 作为 ",
    "message 的最后一个非空行：\n",
    "\n",
    "`CODEY_DELEGATION_V2={\"id\":\"task_name\",\"why\":\"breadth\",\"visual\":false,\"read\":[],\"write\":[],\"checks\":[]}`",
    "\n",
    "\n",
    "`id` 必须等于 `task_name`。只有 `why: \"parallel\"` 时才填写 `branch_calls`，用数组记录各独立分支预计的实质调用数，例如 ",
    "`\"branch_calls\":[3,3]`；其他路由规模只在派发判断中说明，不写入运行时契约。资源路径使用绝对路径，或者给出绝对 `root` ",
    "后使用相对路径。只声明本任务确实会使用的稳定路径；读取可以留空，写入角色的 `write` 不得为空。写入角色还必须提供 1–3 个精确检查，例如 ",
    "`\"checks\":[{\"id\":\"tests\",\"cmd\":\"cargo test -p app\"}]`。运行时会校验理由与角色兼容性、角色能力、预算以及 read/write ",
    "父子路径冲突；重复任务 ID、越权写入和重叠 ownership 仍会被拒绝。\n",
    "\n",
    "### 任务胶囊与验收\n",
    "\n",
    "- 派发消息只携带完成子任务必需的目标、范围、允许操作、ownership 和输出契约，不复制整段对话。\n",
    "- 子代理首行必须是 `status: completed | partial | blocked`，只返回会影响决策的结论、最多 5 条关键证据和明确 gaps；关键证据包含 ",
    "`file:line`、符号名或可复核链接。\n",
    "- 子代理结果只是压缩线索。主代理沿出处抽查；即将修改的确切代码和奠基性文档仍由主代理完整读取。\n",
    "- 写入型子代理的自报测试结果不算机械验收。所有子代理进入终态后，主代理必须按 Stop 门禁给出的 `# codey-accept:<task>:<check>` ",
    "标记逐字重跑契约命令；只有可信的退出状态 `0` 才清偿验收债。失败后修复并重跑，不能改写命令绕过。连续 3 次失败、连续 3 次 Stop 没有新证据，或持续 10 ",
    "分钟无法验证时，门禁会把该项标记为\u{201c}未验证\u{201d}并在一次明确提示后释放；主代理必须向用户报告失败事实，不得声称验收通过。视觉质量仍需主代理查看实际渲染证据。\n",
    "- 多代理证据冲突时比较出处，不按多数票决定；只有高风险且无法确定性验证时才追加独立核验线。\n",
    "\n",
    "### 汇合、异常与接管\n",
    "\n",
    "- 同一批独立任务先全部派发，再进入等待；有活动子代理时只使用 `agents.*` 协调，直至每个代理进入终态。\n",
    "- 每个子代理只用一轮，不复用、不追派，也不得继续派生。失败后默认由主代理接管；只有缩小或改变范围后仍值得独立委派，才允许使用新任务 ID 最多重派一次。\n",
    "- 收到 `CODEY_SUBAGENT_DUPLICATE_TASK_ID` 时，不得重复旧 ID，也不得把拒绝当作完成后立即 Stop。先调用一次无筛选的 ",
    "`agents.list_agents` 对账：原代理存在时等待其终态或消费已有终态结果，明确不存在时由主代理接管；只有任务范围确实改变且仍值得委派时，才可使用全新的 `task_name` ",
    "最多重试一次，并把 `CODEY_DELEGATION_V2.id` 同步改为完全相同的新值。\n",
    "- `MESSAGE` ",
    "或不完整结果只保存证据并继续等待。`completed`、`errored`、`error`、`failed`、`shutdown`、`not_found`、`FINAL_ANSWER` 和 ",
    "`task_complete` 为终态；`running`、`pending_init` 和 `interrupted` 不是终态。\n",
    "- `pending_init` 或运行累计 10 分钟无终态时，先用无筛选的 `agents.list_agents` 对账；仍无终态则只中断一次并继续等待。禁止无限 ",
    "wait、无限重试或静默重派。\n",
    "- 用户新输入使旧批次失效时，先中断活动代理并完成对账，忽略迟到结果。预算账本和未清偿验收债按运行代次与会话恢复；协作工具不可用时不要循环调用不存在的工具。\n",
);

pub(super) const BATCH_RESOLUTION_USAGE_HINT: &str = concat!(
    "`agents.spawn_agent`, `agents.wait_agent`, and every other `agents` collaboration tool are ",
    "direct commentary tools. Call them only through their declared direct tool schemas. Dispatch ",
    "every independent agent planned for the current batch before the first wait, then call ",
    "`agents.wait_agent` before any non-collaboration work. Use `timeout_ms <= 120000`; a mailbox ",
    "update is not completion. If a `MESSAGE` or another partial update needs action, use only the ",
    "relevant `agents.send_message`, `agents.followup_task`, `agents.interrupt_agent`, or ",
    "`agents.list_agents` tool, then return to `agents.wait_agent`. Use `followup_task` only while ",
    "the target's current attempt is still nonterminal and bound; never use it to reactivate a ",
    "terminal, failed, shutdown, not_found, or prior-turn agent. A ",
    "`CODEY_SUBAGENT_FOLLOWUP_REQUIRES_ACTIVE_ATTEMPT` denial happens before the child is woken: do ",
    "not retry or wait for that canonical task to recover; use a fresh `task_name` with the same ",
    "fresh `CODEY_DELEGATION_V2.id` through `agents.spawn_agent`, or let the root take over. Treat ",
    "`FINAL_ANSWER`, `task_complete`, `completed`, `errored`, `error`, `failed`, `shutdown`, and ",
    "`not_found` as terminal; `pending_init`, `running`, and `interrupted` remain nonterminal. If a ",
    "wait result lacks per-agent terminal details, call unfiltered `agents.list_agents` to reconcile ",
    "the full batch. Continue until every spawned agent is terminal. Once the batch settles, call ",
    "`mcp__codey_subagent_control__resolve_batch` with the reported batch number, a unique ",
    "decision_id, and a short reason. Choose exactly one of `spawn_next_batch`, `continue_root`, ",
    "`complete`, or `blocked`; `spawn_next_batch` must be followed by direct `agents.spawn_agent` ",
    "calls in the same response, while `continue_root` must later be replaced by `complete`, ",
    "`blocked`, or `spawn_next_batch` before Stop. If a collaboration tool is unavailable, do not ",
    "loop on an unregistered tool; Codey's runtime gate has bounded stale-state recovery. While ",
    "spawned subagents are active, Codey's runtime gate denies non-collaboration local tools and ",
    "prevents the root turn from finishing. The `functions.exec` tool world is a separate route and ",
    "does not contain collaboration tools.",
);

pub(super) const DIRECT_SCHEMA_USAGE_HINT: &str = concat!(
    "`agents.spawn_agent`, `agents.wait_agent`, and every other `agents` collaboration tool are ",
    "direct commentary tools. Call them only through their declared direct tool schemas. Dispatch ",
    "every independent agent planned for the current batch before the first wait, then call ",
    "`agents.wait_agent` before any non-collaboration work. Use `timeout_ms <= 120000`; a mailbox ",
    "update is not completion. If a `MESSAGE` or another partial update needs action, use only the ",
    "relevant `agents.send_message`, `agents.followup_task`, `agents.interrupt_agent`, or ",
    "`agents.list_agents` tool, then return to `agents.wait_agent`. Treat `FINAL_ANSWER`, ",
    "`task_complete`, `completed`, `errored`, `shutdown`, and `not_found` as terminal; ",
    "`pending_init`, `running`, and `interrupted` remain nonterminal. If a wait result lacks ",
    "per-agent terminal details, call unfiltered `agents.list_agents` to reconcile the full batch. If",
    " a collaboration tool is unavailable, do not loop on an unregistered tool; Codey's runtime gate ",
    "has bounded stale-state recovery. Continue until every spawned agent is terminal. While spawned ",
    "subagents are active, Codey's runtime gate denies non-collaboration local tools and prevents the",
    " root turn from finishing. The `functions.exec` tool world is a separate route and does not ",
    "contain collaboration tools.",
);

pub(super) const TASK_ROUTED_FASTCTX_GUIDANCE: &str = concat!(
    "Codey FastCtx context tools are enabled as direct tools. Route local workspace work by task: use",
    " `mcp__codey_fastctx__inspect_local_file` for focused inspection, `mcp__codey_fastctx__grep` for",
    " content search, `mcp__codey_fastctx__glob` for path discovery, and ",
    "`mcp__codey_fastctx__replace` only for deterministic mechanical replacement. Batch 2-32 ",
    "already-known text files or ranges into one `inspect_local_file(files=[...])` call; for large ",
    "files request only the needed ranges. Pass plain absolute filesystem paths, converting ",
    "URI-shaped local references and Windows paths to a drive-letter path such as `E:/repo/file.ts`. ",
    "Start broad searches with grep's `files_with_matches`, then use `content` with the smallest ",
    "useful context and result limit; use `summary` or `count` only when totals are the requested ",
    "result. Use glob with `filter_mode=project` and stable path sorting unless ignored files or ",
    "modification order are explicitly required. Run replace as dry-run first, set ",
    "`max_replacements`, then inspect or grep the result and run relevant tests; never transparently ",
    "retry a write after transport failure. Follow every Complete or Partial continuation exactly and",
    " do not speculatively request later pages in parallel. FastCtx is a direct-only tool namespace, ",
    "not an MCP Resources server and not a code-mode aggregate; call the tools directly, using ",
    "`tool_search` when a direct tool is deferred. Use terminal commands for builds, tests, Git, ",
    "package managers, metadata or streaming operations, advanced shell semantics, or after the ",
    "applicable FastCtx tool is unavailable or fails. Use CodeGraph only for semantic code ",
    "understanding such as symbols, callers, callees, and call paths. Every tool call must advance ",
    "the requested task; put progress and corrections in commentary.",
);

pub(super) const DIRECT_SUBAGENT_GUIDANCE: &str = concat!(
    "## 子代理使用\n",
    "\n",
    "主动识别可独立推进的检索、实现和核验任务；存在明确分工或上下文隔离收益时，尽早使用子代理，无需用户逐次要求。先做确定边界所需的少量检查，再派发独立任务，不必等主代理完成同一调查后再分工。单步即可完成、步骤无法分离或委派没有实际收益的任务由主代理直接处理；不按文件数量或预计工具调用次数决定是否委派。",
    "\n",
    "\n",
    "纯只读工作最多同时运行 3 个子代理；存在写入型或身份未确认的代理时最多同时运行 2 个。并发限制只约束同时运行数量，不限制后续派发次数。\n",
    "\n",
    "### 派发\n",
    "\n",
    "- 直接调用 `agents.spawn_agent`，按任务选择 ",
    "`codey_quick_scan`、`codey_deep_research`、`codey_visual_analysis`、`codey_worker` 或 ",
    "`codey_visual_worker`；`default` 仅兼容旧配置。`task_name` 只含小写字母、数字和下划线。\n",
    "- `message` 是唯一任务胶囊：写清目标、范围、允许操作、交付格式和必要背景，不复制整段对话，不附加 V1/V2 契约、sidecar、checks 或其他尾行协议。\n",
    "- 修改关键代码或文档时，可先派发独立的只读调查或核验；写入任务明确文件归属，避免重复调查或同时修改同一处。只读角色获得 `files.read`；写入角色获得 ",
    "`command.execute`、`files.read` 和 `workspace.write`。写入角色暂按当前工作区建立互斥锁；实际权限仍由 Codex 原生 ",
    "sandbox、approval policy、permission profile 和 writable roots 决定。\n",
    "\n",
    "### 返回与验收\n",
    "\n",
    "- 每个子代理只执行一轮且不得继续派生。返回首行使用 `status: completed | partial | blocked`，正文只保留影响决策的结论、最多 5 条带 ",
    "`file:line`/符号/链接的证据和明确 gaps；多代理证据冲突时比较出处。\n",
    "- 子代理结果是候选产物，不是验收结论。所有代理结算后，由根代理结合用户要求、变更差异和必要的确定性检查统一验收；Codey 不再创建逐任务机械验收债或强制验收命令。\n",
    "\n",
    "### 生命周期\n",
    "\n",
    "- 先派发不超过当前并发上限的独立任务，再进入 wait/list。任一 attempt 终态或被成功中断并 fence 后，按下一个计划任务的角色重新计算并发上限；存在空余槽位时立即使用新 ",
    "`task_name` 补位，否则继续等待。所有计划任务均已派发后，继续等待剩余活动 attempt 结算。活动 attempt 期间只使用必要的 `agents.*` ",
    "协作工具，普通本地工作和 Stop 仍受生命周期门禁限制。\n",
    "- `MESSAGE` ",
    "只保存证据并继续等待。`completed`、`errored`、`error`、`failed`、`shutdown`、`not_found`、`FINAL_ANSWER` 和 ",
    "`task_complete` 为终态；`pending_init`、`running`、`interrupted` 仍是非终态，除非根代理成功中断并永久放弃该 attempt。\n",
    "- 成功的 `agents.interrupt_agent` 会永久 fence 该 attempt；不要再等待或追派。重复 task ID 时只做一次无筛选 ",
    "`agents.list_agents` 对账：原代理存在则等待或消费结果，不存在则由根代理接管。只有任务范围实质改变时才用全新 task ID 最多重派一次。\n",
    "- 协作工具不可用时不要循环调用；依赖有界的 pending-init、超时和 Stop 恢复路径收敛。\n",
);

pub(super) const DIRECT_COLLABORATION_USAGE_HINT: &str = concat!(
    "`agents.spawn_agent`, `agents.wait_agent`, and other `agents.*` collaboration tools are direct ",
    "commentary tools; never call them through `functions.exec`. Dispatch up to the current ",
    "concurrency limit from the planned independent work before the first wait. While any attempt is ",
    "active, use only the relevant `agents.spawn_agent`, `agents.send_message`, ",
    "`agents.followup_task`, `agents.interrupt_agent`, `agents.list_agents`, or `agents.wait_agent`. ",
    "After a terminal or successfully fenced update, recompute the role-aware concurrency limit; if ",
    "it exposes a slot, immediately use `agents.spawn_agent` with a new `task_name` for the next ",
    "planned, unspawned task; otherwise return to `agents.wait_agent` with `timeout_ms: 30000`. ",
    "`MESSAGE` and mailbox updates are not completion. Use `followup_task` only for a bound ",
    "nonterminal attempt. If `CODEY_SUBAGENT_FOLLOWUP_REQUIRES_ACTIVE_ATTEMPT` is denied, do not ",
    "retry or wait for that target; take over or use a fresh `task_name` for a materially changed ",
    "task. Treat `FINAL_ANSWER`, `task_complete`, `completed`, `errored`, `error`, `failed`, ",
    "`shutdown`, and `not_found` as terminal. A successful root interrupt permanently abandons and ",
    "fences that attempt and settles it for the lifecycle ledger; do not wait for or follow up that ",
    "target. Interrupt revokes child tool access before the provider call, but keeps the writer ",
    "reservation until acknowledgement or terminal reconciliation. Queued followups may still start ",
    "another turn; they cannot restore tool access. A failed interrupt does not release the ",
    "reservation. Match evidence and write reports to the exact task and attempt; never transfer ",
    "another attempt's no-change claim or infer a transport stall from elapsed time alone. If a wait ",
    "times out or lacks per-agent terminal details, call unfiltered `agents.list_agents` before ",
    "waiting again. Continue until all planned work has been spawned and every attempt is terminal or",
    " fenced. Then the root agent validates the combined result and either continues the work or ",
    "finishes. While an attempt is active, Codey's gate blocks non-collaboration tools and Stop. If ",
    "collaboration tools are unavailable, do not loop on an unregistered tool.",
);

pub(super) const DIRECT_FASTCTX_GUIDANCE: &str = concat!(
    "Codey FastCtx context tools are enabled as direct tools. Use ",
    "`mcp__codey_fastctx__inspect_local_file` for focused inspection, `mcp__codey_fastctx__grep` for ",
    "search, `mcp__codey_fastctx__glob` for discovery, and `mcp__codey_fastctx__replace` only for ",
    "deterministic replacement. Batch 2-32 known text files or ranges per inspect call; limit large ",
    "files to needed ranges. A top-level `limit` applies to entries without one. Pass plain absolute ",
    "filesystem paths; convert local URIs and Windows paths to a drive-letter path such as ",
    "`E:/repo/file.ts`. Start broad grep with `files_with_matches`, then request minimal `content`; ",
    "use summary or count only for totals. Glob with `filter_mode=ignore`, stable sorting, and ",
    "`output_mode=details` only when metadata matters. Run replace as dry-run first with ",
    "`max_replacements`, then inspect and test; never transparently retry a write after transport ",
    "failure. Follow every Complete or Partial continuation without parallel page speculation. ",
    "FastCtx is a direct-only tool namespace, not an MCP Resources server or code-mode aggregate; ",
    "call tools directly and use `tool_search` when deferred. Use terminal commands for builds, ",
    "tests, Git, package managers, advanced shell/streaming operations, unsupported metadata, or ",
    "after the applicable FastCtx tool is unavailable or fails. Use CodeGraph only for semantic ",
    "symbols and call paths. Every tool call must advance the task; put progress and corrections in ",
    "commentary.",
);
